apiVersion: v1
kind: Service
metadata:
  name: shp-build-webhook
  namespace: shipwright-build
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    name: shp-build-webhook
