on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Desired tag'
        required: true

name: me
jobs:
    unit:
        runs-on: ubuntu-latest
        steps:
        - name: Verify git version
          run: |
            git version

