on: 
    pull_request:
      branches:
      - main
      - master
    push:
      paths-ignore:
      - 'README.md'
      - 'docs/**'
      branches: 
      - main
      - master
name: Unit, Integration, and E2E Tests
jobs:
    unit:
        runs-on: ubuntu-latest
        steps:
        - name: Verify git version
          run: |
            git version

