name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Desired tag'
        required: true
      tags:
        description: 'Previous tag'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build Release Changelog
      run: |
        git fetch --all --tags --prune --force
        echo -e "# Insert Title\n" > Changes.md
        git log --pretty=format:"%h -  %s - %an" ${{ github.event.inputs.tags }}..HEAD | grep -v "Merge pull" >> Changes.md
        echo -e "## Features\n\n## Fixes\n\n## Backwards incompatible changes\n\n## Docs\n\n## Misc\n\n## Thanks" >> Changes.md    - name: Draft Release
    - name: Draft release
      id: draft_release
      uses: actions/create-release@v1
      with:
        release_name: "Shipwright Build release ${{ github.event.inputs.release }}"
        tag_name: ${{ github.event.inputs.release }}
        body_path: Changes.md
        draft: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Go
      uses: actions/setup-go@v2
    - name: Install Ko
      run: |
        echo '::group:: install ko'
        curl -L https://github.com/google/ko/releases/download/v0.8.0/ko_0.8.0_Linux_x86_64.tar.gz | tar xzf - ko
        chmod +x ./ko
        sudo mv ko /usr/local/bin
        echo '::endgroup::'
    - name: Ko resolve release.yaml
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        IMAGE_HOST: quay.io
        IMAGE: encaladaenrique/eeeoo
      run: make release
    - name: Upload Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.draft_release.outputs.upload_url }} 
        asset_path: ./release.yaml
        asset_name: release.yaml
        asset_content_type: application/x-yaml
